<?php /** @var Zend\View\Renderer\PhpRenderer $this */  ?>
<?php $this->inlineScript()->setAllowArbitraryAttributes(true) ?>

<?php $this->headLink()->prependStylesheet(sprintf('%scss/libs/joint/joint.css', $this->url('assets-workflow-designer'))) ?>

<?php $this->inlineScript()->prependFile(
    sprintf('%sjs/libs/require/require.js', $this->url('assets-workflow-designer')),
    'text/javascript',
    [
        'data-main' => sprintf('%sjs/bootstrap.js', $this->url('assets-workflow-designer')),
    ]
);
?>

<div class="workflow-designer-layout">


</div>